// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/auth/login": {
            "post": {
                "description": "login by wallet",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "login",
                "parameters": [
                    {
                        "description": "login parameters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/localconfig.Login"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/jwt.LoginResponseDto"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/logout": {
            "post": {
                "description": "Refresh by wallet",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Refresh token",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/serializer.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/refresh-token": {
            "post": {
                "description": "Refresh by wallet",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Refresh token",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/jwt.LoginResponseDto"
                        }
                    }
                }
            }
        },
        "/api/v1/web-oriented/ido-active": {
            "get": {
                "description": "ido",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "web-oriented ido-active",
                "parameters": [
                    {
                        "description": "IdoActive parameters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.PageDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.IdoActiveResp"
                        }
                    }
                }
            }
        },
        "/api/v1/web-oriented/ido-active-detail": {
            "get": {
                "description": "ido",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "web-oriented ido-active-detail",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.IdoActiveDetailResp"
                        }
                    }
                }
            }
        },
        "/api/v1/web-oriented/ido-completed": {
            "get": {
                "description": "ido",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "web-oriented ido-completed",
                "parameters": [
                    {
                        "description": "IdoCompleted parameters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.PageDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.IdoCompletedResp"
                        }
                    }
                }
            }
        },
        "/api/v1/web-oriented/ido-launched-detail": {
            "get": {
                "description": "ido",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "web-oriented ido-launched-detail",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.IdoLaunchedDetailResp"
                        }
                    }
                }
            }
        },
        "/api/v1/web-oriented/ido-launched-detail-top10": {
            "get": {
                "description": "ido",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "web-oriented ido-completed",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.IdoLaunchedDetailTop10ListResp"
                        }
                    }
                }
            }
        },
        "/api/v1/web-oriented/ido-upcoming": {
            "get": {
                "description": "ido",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "web-oriented ido-upcoming",
                "parameters": [
                    {
                        "description": "IdoUpcoming parameters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.PageDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.IdoUpcomingResp"
                        }
                    }
                }
            }
        },
        "/api/v1/web-oriented/ido-upcoming-detail": {
            "get": {
                "description": "ido",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "web-oriented ido-upcoming-detail",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.IdoUpcomingDetailResp"
                        }
                    }
                }
            }
        },
        "/api/v1/web-oriented/token": {
            "get": {
                "description": "token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "web-oriented token",
                "parameters": [
                    {
                        "description": "TokenList parameters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.TokenListReqDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.TokenListResp"
                        }
                    }
                }
            },
            "post": {
                "description": "token",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "web-oriented token",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.TokenCreateOrUpdateDto"
                        }
                    },
                    {
                        "type": "file",
                        "description": "Files to upload",
                        "name": "tokenIcons",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Files to upload",
                        "name": "banners",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/serializer.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/web-oriented/user": {
            "post": {
                "description": "game",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "special game",
                "parameters": [
                    {
                        "description": "UserNewOrEdit parameters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.UserCreateOrUpdateDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/serializer.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/web-oriented/user-view-others": {
            "get": {
                "description": "User",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "web-web-oriented user-view-others",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.UserViewOthersResp"
                        }
                    }
                }
            }
        },
        "/api/v1/web-unauthorized/top-creators": {
            "get": {
                "description": "creators",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "web-unauthorized top-creators",
                "parameters": [
                    {
                        "description": "TopCreators  parameters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.PageDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.TopCreatorsResp"
                        }
                    }
                }
            }
        },
        "/api/v1/web-unauthorized/top-tokens": {
            "get": {
                "description": "Tokens",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "web-unauthorized top-tokens",
                "parameters": [
                    {
                        "description": "TopTokens parameters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.PageDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.TopTokensResp"
                        }
                    }
                }
            }
        },
        "/api/v1/web-unauthorized/trending-creators": {
            "get": {
                "description": "creators",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "web-unauthorized trending-creators",
                "parameters": [
                    {
                        "description": "TrendingCreators parameters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.PageDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.TrendingCreatorsResp"
                        }
                    }
                }
            }
        },
        "/api/v1/web-unauthorized/trending-tokens": {
            "get": {
                "description": "Tokens",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "web-unauthorized trending-tokens",
                "parameters": [
                    {
                        "description": "TrendingTokens parameters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.PageDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.TrendingTokensResp"
                        }
                    }
                }
            }
        },
        "/api/v1/web-web-oriented/user-view-others-list": {
            "get": {
                "description": "User",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "web-web-oriented user-view-others",
                "parameters": [
                    {
                        "description": "UserViewOthersList parameters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.PageDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.UserViewOthersListResp"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.PageDto": {
            "type": "object",
            "properties": {
                "pageNumber": {
                    "type": "integer"
                },
                "pageSize": {
                    "type": "integer"
                }
            }
        },
        "jwt.LoginResponseDto": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "object",
                    "properties": {
                        "expire": {
                            "type": "integer"
                        },
                        "token": {
                            "type": "string"
                        }
                    }
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "localconfig.Login": {
            "type": "object",
            "required": [
                "address",
                "chain",
                "message",
                "signature"
            ],
            "properties": {
                "address": {
                    "type": "string",
                    "example": "tb1pk7e88y59xje503pzsknn0z3mgpyvefagf2dlrkvlfxpnugy6shmq7qg7q4"
                },
                "chain": {
                    "type": "string",
                    "example": "Bitcoin"
                },
                "message": {
                    "type": "string",
                    "example": "1710501746195"
                },
                "publicKey": {
                    "type": "string"
                },
                "signature": {
                    "type": "string",
                    "example": "IGSo5ZI0H7xpDizzG/1zAYvljp98GoTGIoVZwMLdYAmkMPBwZyvtbgbE1Vs0SogS3juBko3W9BZ5XpGkJY8JEYc="
                }
            }
        },
        "serializer.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "msg": {
                    "type": "string"
                }
            }
        },
        "service.IdoActiveDetailDto": {
            "type": "object",
            "properties": {
                "commitment": {
                    "type": "string"
                },
                "communityActivit": {
                    "type": "string"
                },
                "communitySize": {
                    "type": "string"
                },
                "contractAddress": {
                    "type": "string"
                },
                "contributed": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "creatorActivity": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "endsIn": {
                    "type": "integer"
                },
                "fdv": {
                    "type": "integer"
                },
                "holders": {
                    "type": "string"
                },
                "idoDate": {
                    "type": "integer"
                },
                "liquidity": {
                    "type": "string"
                },
                "lpContractAddress": {
                    "type": "string"
                },
                "marketCap": {
                    "type": "string"
                },
                "maxSupply": {
                    "type": "integer"
                },
                "meMooScore": {
                    "type": "string"
                },
                "price": {
                    "type": "string"
                },
                "projectCreator": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.ProjectCreatorDto"
                    }
                },
                "projectSocial": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.ProjectSocialDto"
                    }
                },
                "projectWebsite": {
                    "type": "string"
                },
                "socialInfo": {
                    "type": "string"
                },
                "ticker": {
                    "type": "string"
                },
                "tokenImageUrl": {
                    "type": "string"
                },
                "tokenName": {
                    "type": "string"
                },
                "totalRaised": {
                    "type": "string"
                }
            }
        },
        "service.IdoActiveDetailResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/service.IdoActiveDetailDto"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "service.IdoActiveDto": {
            "type": "object",
            "properties": {
                "endsIn": {
                    "type": "integer"
                },
                "meMooScore": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "tokenImageUrl": {
                    "type": "string"
                },
                "tokenName": {
                    "type": "string"
                },
                "totalRaised": {
                    "type": "string"
                }
            }
        },
        "service.IdoActivePaginator": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "next_page": {
                    "type": "integer"
                },
                "offset": {
                    "description": "使用 oneOf 注解标签指定可能的类型\nswagger:allOf\nswagger:discriminator Type",
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "prev_page": {
                    "type": "integer"
                },
                "records": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.IdoActiveDto"
                    }
                },
                "rowStart": {
                    "type": "integer"
                },
                "total_page": {
                    "type": "integer"
                },
                "total_record": {
                    "type": "integer"
                }
            }
        },
        "service.IdoActiveResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/service.IdoActivePaginator"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "service.IdoCompletedDto": {
            "type": "object",
            "properties": {
                "athRoi": {
                    "type": "string"
                },
                "meMooScore": {
                    "type": "string"
                },
                "ticker": {
                    "type": "string"
                },
                "tokenImageUrl": {
                    "type": "string"
                },
                "tokenName": {
                    "type": "string"
                },
                "totalRaised": {
                    "type": "string"
                }
            }
        },
        "service.IdoCompletedPaginator": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "next_page": {
                    "type": "integer"
                },
                "offset": {
                    "description": "使用 oneOf 注解标签指定可能的类型\nswagger:allOf\nswagger:discriminator Type",
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "prev_page": {
                    "type": "integer"
                },
                "records": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.IdoCompletedDto"
                    }
                },
                "rowStart": {
                    "type": "integer"
                },
                "total_page": {
                    "type": "integer"
                },
                "total_record": {
                    "type": "integer"
                }
            }
        },
        "service.IdoCompletedResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/service.IdoCompletedPaginator"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "service.IdoLaunchedDetailDto": {
            "type": "object",
            "properties": {
                "allTimeHigh": {
                    "type": "string"
                },
                "allTimeLow": {
                    "type": "string"
                },
                "commitment": {
                    "type": "string"
                },
                "communityActivit": {
                    "type": "string"
                },
                "communitySize": {
                    "type": "string"
                },
                "contractAddress": {
                    "type": "string"
                },
                "contributed": {
                    "type": "string"
                },
                "count": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "creatorActivity": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "endsIn": {
                    "type": "integer"
                },
                "fdv": {
                    "type": "integer"
                },
                "holders": {
                    "type": "string"
                },
                "idoDate": {
                    "type": "integer"
                },
                "increase1H": {
                    "type": "number"
                },
                "increase24H": {
                    "type": "number"
                },
                "liquidity": {
                    "type": "string"
                },
                "lpContractAddress": {
                    "type": "string"
                },
                "lpLock": {
                    "type": "boolean"
                },
                "marketCap": {
                    "type": "string"
                },
                "maxSupply": {
                    "type": "integer"
                },
                "meMooScore": {
                    "type": "string"
                },
                "price": {
                    "type": "string"
                },
                "projectCreator": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.ProjectCreatorDto"
                    }
                },
                "projectSocial": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.ProjectSocialDto"
                    }
                },
                "projectWebsite": {
                    "type": "string"
                },
                "socialInfo": {
                    "type": "string"
                },
                "ticker": {
                    "type": "string"
                },
                "tokenImageUrl": {
                    "type": "string"
                },
                "tokenName": {
                    "type": "string"
                },
                "totalRaised": {
                    "type": "string"
                },
                "volume24H": {
                    "type": "number"
                }
            }
        },
        "service.IdoLaunchedDetailResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/service.IdoLaunchedDetailDto"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "service.IdoLaunchedDetailTop10ListDto": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "proportion": {
                    "type": "string"
                }
            }
        },
        "service.IdoLaunchedDetailTop10ListPaginator": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "next_page": {
                    "type": "integer"
                },
                "offset": {
                    "description": "使用 oneOf 注解标签指定可能的类型\nswagger:allOf\nswagger:discriminator Type",
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "prev_page": {
                    "type": "integer"
                },
                "records": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.IdoLaunchedDetailTop10ListDto"
                    }
                },
                "rowStart": {
                    "type": "integer"
                },
                "total_page": {
                    "type": "integer"
                },
                "total_record": {
                    "type": "integer"
                }
            }
        },
        "service.IdoLaunchedDetailTop10ListResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/service.IdoLaunchedDetailTop10ListPaginator"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "service.IdoUpcomingDetailDto": {
            "type": "object",
            "properties": {
                "commitment": {
                    "type": "string"
                },
                "communityActivit": {
                    "type": "string"
                },
                "communitySize": {
                    "type": "string"
                },
                "contractAddress": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "creatorActivity": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "endsIn": {
                    "type": "integer"
                },
                "fdv": {
                    "type": "integer"
                },
                "holders": {
                    "type": "string"
                },
                "idoDate": {
                    "type": "integer"
                },
                "liquidity": {
                    "type": "string"
                },
                "lpContractAddress": {
                    "type": "string"
                },
                "marketCap": {
                    "type": "string"
                },
                "maxSupply": {
                    "type": "integer"
                },
                "meMooScore": {
                    "type": "string"
                },
                "projectCreator": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.ProjectCreatorDto"
                    }
                },
                "projectSocial": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.ProjectSocialDto"
                    }
                },
                "projectWebsite": {
                    "type": "string"
                },
                "socialInfo": {
                    "type": "string"
                },
                "ticker": {
                    "type": "string"
                },
                "tokenImageUrl": {
                    "type": "string"
                },
                "tokenName": {
                    "type": "string"
                },
                "totalRaised": {
                    "type": "string"
                }
            }
        },
        "service.IdoUpcomingDetailResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/service.IdoUpcomingDetailDto"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "service.IdoUpcomingDto": {
            "type": "object",
            "properties": {
                "idoDate": {
                    "type": "integer"
                },
                "meMooScore": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "tokenImageUrl": {
                    "type": "string"
                },
                "tokenName": {
                    "type": "string"
                },
                "totalRaised": {
                    "type": "string"
                }
            }
        },
        "service.IdoUpcomingPaginator": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "next_page": {
                    "type": "integer"
                },
                "offset": {
                    "description": "使用 oneOf 注解标签指定可能的类型\nswagger:allOf\nswagger:discriminator Type",
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "prev_page": {
                    "type": "integer"
                },
                "records": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.IdoUpcomingDto"
                    }
                },
                "rowStart": {
                    "type": "integer"
                },
                "total_page": {
                    "type": "integer"
                },
                "total_record": {
                    "type": "integer"
                }
            }
        },
        "service.IdoUpcomingResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/service.IdoUpcomingPaginator"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "service.ProjectCreatorDto": {
            "type": "object",
            "properties": {
                "creatorAddress": {
                    "type": "string"
                },
                "twitter": {
                    "type": "string"
                },
                "userName": {
                    "type": "string"
                }
            }
        },
        "service.ProjectSocialDto": {
            "type": "object",
            "properties": {
                "socialType": {
                    "type": "string"
                },
                "socialUrl": {
                    "type": "string"
                }
            }
        },
        "service.TokenCreateOrUpdateDto": {
            "type": "object",
            "required": [
                "description",
                "ticker",
                "tokenName",
                "twitter"
            ],
            "properties": {
                "contractAddress": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "lPContractAddress": {
                    "type": "string"
                },
                "otherLinkStr": {
                    "type": "string"
                },
                "pinnedTwitterLinkStr": {
                    "type": "string"
                },
                "preLaunchDuration": {
                    "description": "IMMEDIATE、1DAY、3DAY",
                    "type": "string"
                },
                "preMarketAcquisition": {
                    "type": "string"
                },
                "projectName": {
                    "type": "string"
                },
                "ticker": {
                    "type": "string"
                },
                "tokenDescription": {
                    "type": "string"
                },
                "tokenName": {
                    "type": "string"
                },
                "twitter": {
                    "type": "string"
                }
            }
        },
        "service.TokenListDto": {
            "type": "object",
            "properties": {
                "launchDate": {
                    "type": "integer"
                },
                "meMooScore": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "tokenImageUrl": {
                    "type": "string"
                },
                "tokenName": {
                    "type": "string"
                },
                "totalRaised": {
                    "type": "string"
                }
            }
        },
        "service.TokenListPaginator": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "next_page": {
                    "type": "integer"
                },
                "offset": {
                    "description": "使用 oneOf 注解标签指定可能的类型\nswagger:allOf\nswagger:discriminator Type",
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "prev_page": {
                    "type": "integer"
                },
                "records": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.TokenListDto"
                    }
                },
                "rowStart": {
                    "type": "integer"
                },
                "total_page": {
                    "type": "integer"
                },
                "total_record": {
                    "type": "integer"
                }
            }
        },
        "service.TokenListReqDto": {
            "type": "object",
            "properties": {
                "pageNumber": {
                    "type": "integer"
                },
                "pageSize": {
                    "type": "integer"
                }
            }
        },
        "service.TokenListResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/service.TokenListPaginator"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "service.TopCreatorsDto": {
            "type": "object",
            "properties": {
                "accumulativeATHMarketCap": {
                    "type": "number"
                },
                "accumulativeHolders": {
                    "type": "integer"
                },
                "accumulativeMarketCap": {
                    "type": "number"
                },
                "creatorsName": {
                    "type": "string"
                },
                "tokensCreatedNum": {
                    "type": "integer"
                },
                "topTokenMarketCap": {
                    "type": "number"
                },
                "userProfileImageUrl": {
                    "type": "string"
                }
            }
        },
        "service.TopCreatorsPaginator": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "next_page": {
                    "type": "integer"
                },
                "offset": {
                    "description": "使用 oneOf 注解标签指定可能的类型\nswagger:allOf\nswagger:discriminator Type",
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "prev_page": {
                    "type": "integer"
                },
                "records": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.TopCreatorsDto"
                    }
                },
                "rowStart": {
                    "type": "integer"
                },
                "total_page": {
                    "type": "integer"
                },
                "total_record": {
                    "type": "integer"
                }
            }
        },
        "service.TopCreatorsResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/service.TopCreatorsPaginator"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "service.TopTokensDto": {
            "type": "object",
            "properties": {
                "increase1H": {
                    "type": "number"
                },
                "increase24H": {
                    "type": "number"
                },
                "meMooScore": {
                    "type": "string"
                },
                "price": {
                    "type": "string"
                },
                "tokenImageUrl": {
                    "type": "string"
                },
                "tokenName": {
                    "type": "string"
                },
                "topTokenMarketCap": {
                    "type": "number"
                },
                "volume24H": {
                    "type": "number"
                }
            }
        },
        "service.TopTokensPaginator": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "next_page": {
                    "type": "integer"
                },
                "offset": {
                    "description": "使用 oneOf 注解标签指定可能的类型\nswagger:allOf\nswagger:discriminator Type",
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "prev_page": {
                    "type": "integer"
                },
                "records": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.TopTokensDto"
                    }
                },
                "rowStart": {
                    "type": "integer"
                },
                "total_page": {
                    "type": "integer"
                },
                "total_record": {
                    "type": "integer"
                }
            }
        },
        "service.TopTokensResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/service.TopTokensPaginator"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "service.TrendingCreatorsDto": {
            "type": "object",
            "properties": {
                "accumulativeATHMarketCap": {
                    "type": "number"
                },
                "accumulativeHolders": {
                    "type": "integer"
                },
                "accumulativeHoldersGrowth": {
                    "type": "integer"
                },
                "accumulativeMarketCap": {
                    "type": "number"
                },
                "creatorsAddress": {
                    "type": "string"
                },
                "creatorsName": {
                    "type": "string"
                },
                "tokensCreatedNum": {
                    "type": "integer"
                },
                "topTokenMarketCap": {
                    "type": "number"
                },
                "userProfileImageUrl": {
                    "type": "string"
                }
            }
        },
        "service.TrendingCreatorsPaginator": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "next_page": {
                    "type": "integer"
                },
                "offset": {
                    "description": "使用 oneOf 注解标签指定可能的类型\nswagger:allOf\nswagger:discriminator Type",
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "prev_page": {
                    "type": "integer"
                },
                "records": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.TrendingCreatorsDto"
                    }
                },
                "rowStart": {
                    "type": "integer"
                },
                "total_page": {
                    "type": "integer"
                },
                "total_record": {
                    "type": "integer"
                }
            }
        },
        "service.TrendingCreatorsResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/service.TrendingCreatorsPaginator"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "service.TrendingTokensDto": {
            "type": "object",
            "properties": {
                "increase1H": {
                    "type": "number"
                },
                "increase24H": {
                    "type": "number"
                },
                "meMooScore": {
                    "type": "string"
                },
                "price": {
                    "type": "string"
                },
                "tokenImageUrl": {
                    "type": "string"
                },
                "tokenName": {
                    "type": "string"
                },
                "topTokenMarketCap": {
                    "type": "number"
                },
                "volume24H": {
                    "type": "number"
                }
            }
        },
        "service.TrendingTokensPaginator": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "next_page": {
                    "type": "integer"
                },
                "offset": {
                    "description": "使用 oneOf 注解标签指定可能的类型\nswagger:allOf\nswagger:discriminator Type",
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "prev_page": {
                    "type": "integer"
                },
                "records": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.TrendingTokensDto"
                    }
                },
                "rowStart": {
                    "type": "integer"
                },
                "total_page": {
                    "type": "integer"
                },
                "total_record": {
                    "type": "integer"
                }
            }
        },
        "service.TrendingTokensResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/service.TrendingTokensPaginator"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "service.UserCreateOrUpdateDto": {
            "type": "object",
            "properties": {
                "twitter": {
                    "type": "string"
                },
                "userBio": {
                    "type": "string"
                },
                "userName": {
                    "type": "string"
                },
                "websiteUrl": {
                    "type": "string"
                }
            }
        },
        "service.UserViewOthersDto": {
            "type": "object",
            "properties": {
                "CreatorTwitter": {
                    "type": "string"
                },
                "accumulativeATHMarketCap": {
                    "type": "number"
                },
                "accumulativeHolders": {
                    "type": "integer"
                },
                "accumulativeHoldersGrowth": {
                    "type": "integer"
                },
                "accumulativeMarketCap": {
                    "type": "number"
                },
                "creatorAddress": {
                    "type": "string"
                },
                "creatorWebsiteUrl": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "imageUrl": {
                    "type": "string"
                },
                "projectSocial": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.ProjectSocialDto"
                    }
                },
                "tokenName": {
                    "type": "string"
                },
                "tokensCreatedNum": {
                    "type": "integer"
                }
            }
        },
        "service.UserViewOthersListDto": {
            "type": "object",
            "properties": {
                "emotion": {
                    "description": "WIF、FOMO、LEASH",
                    "type": "string"
                },
                "imageUrl": {
                    "type": "string"
                },
                "launchDate": {
                    "type": "integer"
                },
                "meMooScore": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "tokenName": {
                    "type": "string"
                },
                "totalRaised": {
                    "type": "string"
                }
            }
        },
        "service.UserViewOthersListPaginator": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "next_page": {
                    "type": "integer"
                },
                "offset": {
                    "description": "使用 oneOf 注解标签指定可能的类型\nswagger:allOf\nswagger:discriminator Type",
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "prev_page": {
                    "type": "integer"
                },
                "records": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.UserViewOthersListDto"
                    }
                },
                "rowStart": {
                    "type": "integer"
                },
                "total_page": {
                    "type": "integer"
                },
                "total_record": {
                    "type": "integer"
                }
            }
        },
        "service.UserViewOthersListResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/service.UserViewOthersListPaginator"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "service.UserViewOthersResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/service.UserViewOthersDto"
                },
                "msg": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
